In [3]:
from src.analysis import *

df = top_streets()
df1 = injury_percentage_by_crash()
df2 = peak_crash_hour_month()

In [4]:
df.head()

   STREET_NAME  total_injuries
0  WESTERN AVE          4145.0
1   PULASKI RD          4113.0
2   CICERO AVE          3721.0
3  ASHLAND AVE          3604.0
4   HALSTED ST          3468.0

In [5]:
df1.head()

  FIRST_CRASH_TYPE  injury_percentage
0       PEDESTRIAN           88.23712
1     PEDALCYCLIST           72.51345
2            TRAIN           51.28205
3       OVERTURNED           46.08076
4          HEAD ON           36.98975

In [6]:
df2.head()

   CRASH_MONTH  CRASH_HOUR  total_crashes  rnk
0            1          15           4408    1
1            2          15           4525    1
2            3          15           4610    1
3            4          15           3884    1
4            5          15           4727    1